#include "ccvm/frontend/ir_generator.h"

namespace ccvm {
namespace frontend {

String IRModule::to_string() const {
    String result = "; CCVM IR Module: " + module_name + "\n";
    result += "; Generated by CCVM Frontend v0.1.0\n\n";
    
    for (const auto& global : globals) {
        result += global + "\n";
    }
    if (!globals.empty()) result += "\n";
    
    for (const auto& func : functions) {
        result += "func " + func.name + "(";
        for (size_t i = 0; i < func.parameters.size(); ++i) {
            if (i > 0) result += ", ";
            result += func.parameters[i].type + " %" + func.parameters[i].name;
        }
        result += ") -> " + func.return_type + " {\n";
        
        for (const auto& inst : func.body) {
            result += "  " + inst + "\n";
        }
        
        result += "}\n\n";
    }
    
    return result;
}

String IRGenerator::new_temp() {
    return "%t" + std::to_string(temp_counter_++);
}

String IRGenerator::generate_expression(Ptr<Expression> expr) {
    if (!expr) return "null";
    
    auto int_lit = std::dynamic_pointer_cast<IntegerLiteral>(expr);
    if (int_lit) {
        return std::to_string(int_lit->getValue());
    }
    
    auto float_lit = std::dynamic_pointer_cast<FloatLiteral>(expr);
    if (float_lit) {
        return std::to_string(float_lit->getValue()) + "f64";
    }
    
    auto ident = std::dynamic_pointer_cast<IdentifierExpression>(expr);
    if (ident) {
        String name = ident->getName();
        bool is_alloca = false;
        for (const auto& a : alloca_vars_) {
            if (a == name) { is_alloca = true; break; }
        }
        if (is_alloca) {
            String loaded = new_temp();
            current_block_.push_back(loaded + " = load i64, ptr %" + name);
            return loaded;
        }
        return "%" + name;
    }
    
    auto bin = std::dynamic_pointer_cast<BinaryExpression>(expr);
    if (bin) {
        String left = generate_expression(bin->getLeft());
        String right = generate_expression(bin->getRight());
        String result = new_temp();
        
        String op;
        switch (bin->getOperator()) {
            case BinaryExpression::Operator::ADD: op = "add"; break;
            case BinaryExpression::Operator::SUB: op = "sub"; break;
            case BinaryExpression::Operator::MUL: op = "mul"; break;
            case BinaryExpression::Operator::DIV: op = "sdiv"; break;
            case BinaryExpression::Operator::ASSIGN: op = "store"; break;
            case BinaryExpression::Operator::LT: op = "icmp slt"; break;
            case BinaryExpression::Operator::GT: op = "icmp sgt"; break;
            case BinaryExpression::Operator::LE: op = "icmp sle"; break;
            case BinaryExpression::Operator::GE: op = "icmp sge"; break;
            case BinaryExpression::Operator::EQ: op = "icmp eq"; break;
            case BinaryExpression::Operator::NE: op = "icmp ne"; break;
            default: op = "add"; break;
        }
        
        if (op == "store") {
            // For store: left must be an alloca address (not loaded), right is the value
            String left_addr;
            auto left_ident = std::dynamic_pointer_cast<IdentifierExpression>(bin->getLeft());
            if (left_ident) {
                String name = left_ident->getName();
                bool is_alloca = false;
                for (const auto& a : alloca_vars_) {
                    if (a == name) { is_alloca = true; break; }
                }
                if (is_alloca) {
                    left_addr = "%" + name;
                } else {
                    left_addr = left;
                }
            } else {
                left_addr = left;
            }
            current_block_.push_back("store i64 " + right + ", ptr " + left_addr);
        } else if (op.substr(0, 4) == "icmp") {
            current_block_.push_back(result + " = " + op + " i64 " + left + ", " + right);
        } else {
            current_block_.push_back(result + " = " + op + " i64 " + left + ", " + right);
        }
        return result;
    }
    
    auto call = std::dynamic_pointer_cast<CallExpression>(expr);
    if (call) {
        auto callee = std::dynamic_pointer_cast<IdentifierExpression>(call->getCallee());
        String func_name = callee ? callee->getName() : "unknown";
        
        Vector<String> args;
        for (const auto& arg : call->getArguments()) {
            args.push_back(generate_expression(arg));
        }
        
        String result = new_temp();
        String arg_str;
        for (size_t i = 0; i < args.size(); ++i) {
            if (i > 0) arg_str += ", ";
            arg_str += "i64 " + args[i];
        }
        
        current_block_.push_back(result + " = call i64 @" + func_name + "(" + arg_str + ")");
        return result;
    }
    
    return "0";
}

void IRGenerator::generate_statement(Ptr<ASTNode> stmt) {
    if (!stmt) return;
    
    auto var_decl = std::dynamic_pointer_cast<VariableDeclaration>(stmt);
    if (var_decl) {
        generate_variable_decl(var_decl);
        return;
    }
    
    auto expr_stmt = std::dynamic_pointer_cast<ExpressionStatement>(stmt);
    if (expr_stmt) {
        generate_expression(expr_stmt->getExpression());
        return;
    }
    
    auto return_stmt = std::dynamic_pointer_cast<ReturnStatement>(stmt);
    if (return_stmt) {
        if (return_stmt->getValue()) {
            String value = generate_expression(return_stmt->getValue());
            if (value.size() > 1 && value[0] == '%') {
                String var_name = value.substr(1);
                bool is_alloca = false;
                for (const auto& a : alloca_vars_) {
                    if (a == var_name) { is_alloca = true; break; }
                }
                if (is_alloca) {
                    String loaded = new_temp();
                    current_block_.push_back(loaded + " = load i64, ptr " + value);
                    value = loaded;
                }
            }
            current_block_.push_back("ret i64 " + value);
        } else {
            current_block_.push_back("ret void");
        }
        return;
    }
    
    auto if_stmt = std::dynamic_pointer_cast<IfStatement>(stmt);
    if (if_stmt) {
        String cond = generate_expression(if_stmt->getCondition());
        String then_label = new_temp();
        String else_label = new_temp();
        String end_label = new_temp();
        
        current_block_.push_back("br i1 " + cond + ", label " + then_label + ", label " + else_label);
        
        current_block_.push_back(then_label + ":");
        generate_statement(if_stmt->getThenStatement());
        current_block_.push_back("br label " + end_label);
        
        current_block_.push_back(else_label + ":");
        if (if_stmt->hasElseStatement()) {
            generate_statement(if_stmt->getElseStatement());
        } else {
            current_block_.push_back("br label " + end_label);
        }
        
        current_block_.push_back(end_label + ":");
        return;
    }
    
    auto while_stmt = std::dynamic_pointer_cast<WhileStatement>(stmt);
    if (while_stmt) {
        String cond_label = new_temp();
        String body_label = new_temp();
        String end_label = new_temp();
        
        current_block_.push_back("br label " + cond_label);
        current_block_.push_back(cond_label + ":");
        
        String cond = generate_expression(while_stmt->getCondition());
        current_block_.push_back("br i1 " + cond + ", label " + body_label + ", label " + end_label);
        
        current_block_.push_back(body_label + ":");
        generate_statement(while_stmt->getBody());
        current_block_.push_back("br label " + cond_label);
        
        current_block_.push_back(end_label + ":");
        return;
    }
    
    auto for_stmt = std::dynamic_pointer_cast<ForStatement>(stmt);
    if (for_stmt) {
        String cond_label = new_temp();
        String body_label = new_temp();
        String inc_label = new_temp();
        String end_label = new_temp();
        
        if (for_stmt->getInit()) {
            generate_statement(for_stmt->getInit());
        }
        
        current_block_.push_back("br label " + cond_label);
        current_block_.push_back(cond_label + ":");
        
        if (for_stmt->getCondition()) {
            String cond = generate_expression(for_stmt->getCondition());
            current_block_.push_back("br i1 " + cond + ", label " + body_label + ", label " + end_label);
        } else {
            current_block_.push_back("br label " + body_label);
        }
        
        current_block_.push_back(body_label + ":");
        generate_statement(for_stmt->getBody());
        current_block_.push_back("br label " + inc_label);
        
        current_block_.push_back(inc_label + ":");
        if (for_stmt->getIncrement()) {
            generate_expression(for_stmt->getIncrement());
        }
        current_block_.push_back("br label " + cond_label);
        
        current_block_.push_back(end_label + ":");
        return;
    }
    
    auto compound = std::dynamic_pointer_cast<CompoundStatement>(stmt);
    if (compound) {
        for (const auto& s : compound->getChildren()) {
            generate_statement(s);
        }
        return;
    }
}

void IRGenerator::generate_function_decl(Ptr<FunctionDeclaration> decl) {
    if (!decl) return;
    
    IRFunction func;
    func.name = decl->getName();
    func.return_type = "i64";
    
    for (const auto& param : decl->getParameters()) {
        IRFunction::Parameter p;
        p.name = param->getName();
        p.type = "i64";
        func.parameters.push_back(p);
    }
    
    module_.functions.push_back(func);
}

void IRGenerator::generate_function_def(Ptr<FunctionDefinition> def) {
    if (!def) return;
    
    current_function_ = def->getName();
    current_block_.clear();
    temp_counter_ = 0;
    alloca_vars_.clear();
    
    String entry_label = "entry";
    current_block_.push_back(entry_label + ":");
    
    auto body = def->getBody();
    if (body) {
        generate_statement(body);
    }
    
    IRFunction func;
    func.name = def->getName();
    func.return_type = "i64";
    
    for (const auto& param : def->getParameters()) {
        IRFunction::Parameter p;
        p.name = param->getName();
        p.type = "i64";
        func.parameters.push_back(p);
    }
    
    func.body = current_block_;
    module_.functions.push_back(func);
}

void IRGenerator::generate_variable_decl(Ptr<VariableDeclaration> decl) {
    if (!decl) return;
    
    String name = decl->getName();
    String alloc = "%" + name + " = alloca i64";
    current_block_.push_back(alloc);
    alloca_vars_.push_back(name);
    
    if (decl->getInitializer()) {
        String value = generate_expression(decl->getInitializer());
        current_block_.push_back("store i64 " + value + ", ptr %" + name);
    }
}

void IRGenerator::generate(ASTNode& node) {
    module_.module_name = "main";
    
    auto tu = dynamic_cast<TranslationUnit*>(&node);
    if (!tu) return;
    
    for (const auto& decl : tu->getDeclarations()) {
        auto func_def = dynamic_cast<FunctionDefinition*>(decl.get());
        if (func_def) {
            generate_function_def(std::dynamic_pointer_cast<FunctionDefinition>(decl));
            continue;
        }
        
        auto func_decl = dynamic_cast<FunctionDeclaration*>(decl.get());
        if (func_decl) {
            generate_function_decl(std::dynamic_pointer_cast<FunctionDeclaration>(decl));
            continue;
        }
        
        auto var_decl = dynamic_cast<VariableDeclaration*>(decl.get());
        if (var_decl) {
            current_block_.clear();
            generate_variable_decl(std::dynamic_pointer_cast<VariableDeclaration>(decl));
            
            IRFunction func;
            func.name = "global_init";
            func.return_type = "void";
            func.body = current_block_;
            module_.functions.push_back(func);
            continue;
        }
    }
}

String IRGenerator::get_ir() const {
    return module_.to_string();
}

} // namespace frontend
} // namespace ccvm
